version: '3.3'

services:
    #database engine service
    postgres:
        container_name: postgres_todo
        image: postgres:latest
        restart: always
        networks:
            - todo
        ports:
            - 5432:5432
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin4_todo
        environment:
            - PGADMIN_DEFAULT_EMAIL=${DBA_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${DBA_PASSWORD}
        networks:
            - todo
        ports:
            - '5050:80'
        depends_on:
            - postgres
networks:
    todo:
        driver: bridge
